// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID    int64 `json:"id"`
	AccID int64 `json:"acc_id"`
	// Can be positive or negative.
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Transfer struct {
	ID        int64     `json:"id"`
	FromAccID int64     `json:"from_acc_id"`
	ToAccID   int64     `json:"to_acc_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username    string    `json:"username"`
	Pass        string    `json:"pass"`
	FullName    string    `json:"full_name"`
	Email       string    `json:"email"`
	PassChanged time.Time `json:"pass_changed"`
	CreatedAt   time.Time `json:"created_at"`
}
